### DISCUSSION TITLE
Comments on the example

### DISCUSSION THREAD

**Discussion by mbwhite** [hyperledgendary/fabric-sail#8] [General]
Using the IRB example, not specifically to critique IRB, but it's a more fully formed example
---

General: My working assumption is that this is point in time statement of the overall structure

```
network:
  name: irb
  domain: localho.st

  #  what is namespace? it might be confusing with a namespace associated to a chaincode
  namespace: test-network
```

On the above, A Fabric Network can exist across multiple cloud providers, and potentially across multiple domains. For example the Ansible collection has support for multi-zone setup. Common Channels and Orderers, but the peers aren't in the same.

On organizations that come next, I can see a case where some organizations don't want to share exactly how many peers they have.
  
```  
organizations:
    - name: orderer-org
      orderers:
        - name: orderers
          count: 3

    - name: provider-org
      peers:
        - name: provider-peer1
          anchor: true
      clients:
        - name: provider-cli1
          image: "fpc/fpc-cli:main"
```
I think a description of 'clients' here is a potential mistake. I'm seeing this as client applications; it's not the job of this file to describe the client network.  What I think should be here is someway of specing the information that client applications will needed.

Basically, the connection profile, including CAs etc. what does a client need to connect 

```
    - name: investigator-org
      peers:
        - name: investigator-peer1
          anchor: true
          version: 2.4.4
```
Like the inclusion of the version as that then permits a description of the network to be written in a new file, that for example Ansible can then migrate.
```
      clients: # optional: some container that is provisioned with client credentials
        - name: provider-cli1
          image: "fpc/fpc-cli:main"

    - name: experimenter-org
      peers:
        - name: experimenter-peer1
          anchor: true
          image: "some-custom-fabric-peer-image:v2.4.4"
      clients:
        - name: provider-cli1
          image: "fpc/fpc-cli:main"

  channels:
    - name: mychannel
      organizations:
        - provider-org
        - investigator-org
        - experimenter-org
```
Lot more channel options but they can be added here I'm sure. 

```

  chaincode:
    - name: experimener-approval-service
      version: "98aed61c91f258a37c68ed4943297695647ec7bbe6008cc111b0a12650ebeb91"
      image: "fpc/irb-experiment:main"
      peers: [provider-peer1, investigator-peer1, experimenter-peer1]
      channels:
        - name: mychannel
          policy: "OutOf(2, 'provider-org.member', 'investigator-org.member', 'experimenter-org')"

    - name: fpc-registry
      version: "v1.0"
      image: "fpc/fpc-ercc:main"
      #      peers: ALL By default
      channels:
        - name: mychannel
          policy: "AND('provider-org.member', 'investigator-org.member', 'experimenter-org')"
```

Being able to just point at something and say that's the chaincode is good
