### ISSUE TITLE
Ideas for additional configuration ...

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledgendary/fabric-sail#4]
The current sail syntax is nice ... here a few additional options I would find useful. Dumping my ideas here ...

```
chaincode:
    - name: asset-transfer
      version: v0.1.1
      image: my-chaincode-image:v1
      peers: [orgB-peer1, orgB-peer2, orgA-peer1, ...]
      channels:
        - name: mychannel
          policy: "OR('org1.member', 'org2.member')"
```

`image`: docker image name with tag. If no tag set, `latest` is used.
Either `package` or `image` is set. 

`peers`: a list of peers where the chaincode is installed. What are the default peers?

Does it make sense to also define a set of "client nodes" equipped with the crypto material to run `peer` commands or deploy a fabric client sdk application?

What about setting `FABRIC_LOGGING_SPEC` for each peer or for all?

Oh and could we override certain keys in the `core.yaml` of a peer and the `orderer.yaml`?

What about enabling Idemix?

WDYT?
